/**
 * Tripletex connector — Norwegian accounting platform.
 *
 * Auth: Tripletex uses session tokens. The consumer token is a long-lived credential
 * obtained from Tripletex support; the employee token is generated by the user.
 * These are exchanged for a short-lived session token (expires in ~24 h) via
 * POST /token/session. We use prepareRequest to inject the session token and
 * ctx.state.update to refresh it atomically when expired.
 *
 * Docs: https://tripletex.no/v2-docs/
 */
import type {
  Connector,
  ConnectorContext,
  EntityDefinition,
  ReadBatch,
  ReadRecord,
  InsertRecord,
  InsertResult,
  UpdateRecord,
  UpdateResult,
  DeleteResult,
  WebhookBatch,
} from "@opensync/sdk";
import { AuthError, ConnectorError, RateLimitError } from "@opensync/sdk";

// ─── Session token management ─────────────────────────────────────────────────

interface SessionToken {
  value: string;
  expiresAt: string; // ISO 8601
}

function isExpired(token: SessionToken): boolean {
  return new Date(token.expiresAt) <= new Date(Date.now() + 60_000); // refresh 1 min early
}

/** Exchange consumer + employee tokens for a session token. */
async function fetchSessionToken(
  ctx: ConnectorContext
): Promise<SessionToken> {
  const base = ctx.config["baseUrl"] as string;
  const consumerToken = ctx.config["consumerToken"] as string;
  const employeeToken = ctx.config["employeeToken"] as string;

  // Session token endpoint does not inject auth — call global fetch directly
  // (ctx.http would also work here since prepareRequest safe-guards against recursion,
  // but using the raw fetch makes intent explicit).
  const res = await fetch(
    `${base}/token/session/:create?consumerToken=${consumerToken}&employeeToken=${employeeToken}&expirationDate=${nextDay()}`,
    { method: "PUT" }
  );

  if (res.status === 401 || res.status === 403) {
    throw new AuthError("Tripletex: invalid consumer or employee token");
  }
  if (!res.ok) {
    throw new ConnectorError(
      `Tripletex: session token request failed with ${res.status}`,
      "SESSION_TOKEN_ERROR",
      res.status >= 500
    );
  }

  const body = (await res.json()) as {
    value: { token: string; expirationDate: string };
  };
  return {
    value: body.value.token,
    expiresAt: body.value.expirationDate,
  };
}

function nextDay(): string {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  return d.toISOString().slice(0, 10);
}

async function getSessionToken(ctx: ConnectorContext): Promise<string> {
  const token = await ctx.state.update<SessionToken>(
    "sessionToken",
    async (current) => {
      if (current && !isExpired(current)) return current;
      return fetchSessionToken(ctx);
    },
    15_000
  );
  return token.value;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function throwForStatus(res: Response, context: string): never {
  if (res.status === 401 || res.status === 403) {
    throw new AuthError(`Tripletex: authentication failed (${context})`);
  }
  if (res.status === 429) {
    throw new RateLimitError(`Tripletex: rate limited (${context})`);
  }
  throw new ConnectorError(
    `Tripletex: API error ${res.status} (${context})`,
    "API_ERROR",
    res.status >= 500
  );
}

/** Paginate through a Tripletex list endpoint using `from`/`count` offset paging. */
async function* paginate<T>(
  ctx: ConnectorContext,
  path: string,
  params: Record<string, string> = {}
): AsyncGenerator<T[]> {
  const base = ctx.config["baseUrl"] as string;
  let from = 0;
  const count = 100;

  while (true) {
    const p = new URLSearchParams({ ...params, from: String(from), count: String(count) });
    const res = await ctx.http(`${base}${path}?${p}`);
    if (!res.ok) throwForStatus(res, `GET ${path}`);

    const body = (await res.json()) as {
      values: T[];
      fullResultSize: number;
    };

    yield body.values;

    from += body.values.length;
    if (from >= body.fullResultSize || body.values.length === 0) break;
  }
}

// ─── Webhook helpers ─────────────────────────────────────────────────────────

/** Wildcard event patterns to subscribe to, one per entity. */
const ENTITY_SUBSCRIPTION_EVENT: Record<string, string> = {
  customer: "customer.*",
  invoice: "invoice.*",
};

/**
 * Register a Tripletex webhook subscription for a single entity.
 * The callback URL includes `?entity=<name>` so handleWebhook can identify
 * which entity the payload belongs to without parsing the event string.
 */
async function registerSubscription(
  entity: string,
  ctx: ConnectorContext
): Promise<void> {
  const base = ctx.config["baseUrl"] as string;
  const targetUrl = `${ctx.webhookUrl}?entity=${entity}`;
  const res = await ctx.http(`${base}/event/subscription`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ event: ENTITY_SUBSCRIPTION_EVENT[entity], targetUrl }),
  });
  if (!res.ok) throwForStatus(res, `POST /event/subscription (${ENTITY_SUBSCRIPTION_EVENT[entity]})`);
  const body = (await res.json()) as { value: { id: number } };
  await ctx.state.set(`webhookSubscription_${entity}`, body.value.id);
}

/** Deregister the subscription stored for a single entity. */
async function deregisterSubscription(
  entity: string,
  ctx: ConnectorContext
): Promise<void> {
  const base = ctx.config["baseUrl"] as string;
  const id = await ctx.state.get<number>(`webhookSubscription_${entity}`);
  if (!id) return;
  const res = await ctx.http(`${base}/event/subscription/${id}`, { method: "DELETE" });
  if (!res.ok && res.status !== 404) throwForStatus(res, `DELETE /event/subscription/${id}`);
  await ctx.state.delete(`webhookSubscription_${entity}`);
}

// ─── Entities ─────────────────────────────────────────────────────────────────

const customerEntity: EntityDefinition = {
  name: "customer",

  schema: {
    id: {
      description: "Tripletex internal customer ID.",
      type: "number",
      immutable: true,
    },
    name: { description: "Customer display name.", type: "string", required: true },
    organizationNumber: {
      description: "Norwegian organisation number (9 digits).",
      type: "string",
    },
    email: { description: "Primary contact email.", type: "string" },
    phoneNumber: { description: "Primary phone number.", type: "string" },
    isSupplier: { description: "True if this contact is also a supplier.", type: "boolean" },
    isCustomer: { description: "True if this contact is a customer.", type: "boolean" },
    customer: {
      description: "True if the contact has a customer relationship.",
      type: "boolean",
    },
  },

  async onEnable(ctx: ConnectorContext): Promise<void> {
    await registerSubscription("customer", ctx);
  },

  async onDisable(ctx: ConnectorContext): Promise<void> {
    await deregisterSubscription("customer", ctx);
  },

  async *read(ctx: ConnectorContext, since?: string): AsyncIterable<ReadBatch> {
    const params: Record<string, string> = {};
    if (since) params["changedSince"] = since;

    let maxChanged: string | undefined;
    for await (const page of paginate<Record<string, unknown>>(ctx, "/customer", params)) {
      for (const item of page) {
        const changed = item["changedDate"] as string | undefined;
        if (changed && (!maxChanged || changed > maxChanged)) maxChanged = changed;
      }
      yield {
        records: page.map((item) => ({
          id: String(item["id"]),
          data: item,
        })),
        since: maxChanged ?? since,
      };
    }
  },

  async lookup(ids: string[], ctx: ConnectorContext): Promise<ReadRecord[]> {
    const base = ctx.config["baseUrl"] as string;
    const results: ReadRecord[] = [];
    // Tripletex has no batch read — loop through IDs.
    for (const id of ids) {
      const res = await ctx.http(`${base}/customer/${id}`);
      if (res.status === 404) continue;
      if (!res.ok) throwForStatus(res, `GET /customer/${id}`);
      const body = (await res.json()) as { value: Record<string, unknown> };
      results.push({ id, data: body.value });
    }
    return results;
  },

  async *insert(
    records: AsyncIterable<InsertRecord>,
    ctx: ConnectorContext
  ): AsyncIterable<InsertResult> {
    const base = ctx.config["baseUrl"] as string;
    for await (const record of records) {
      const res = await ctx.http(`${base}/customer`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(record.data),
      });
      if (!res.ok) throwForStatus(res, "POST /customer");
      const body = (await res.json()) as { value: { id: number } & Record<string, unknown> };
      yield {
        id: String(body.value.id),
        data: body.value as Record<string, unknown>,
      };
    }
  },

  async *update(
    records: AsyncIterable<UpdateRecord>,
    ctx: ConnectorContext
  ): AsyncIterable<UpdateResult> {
    const base = ctx.config["baseUrl"] as string;
    for await (const record of records) {
      const res = await ctx.http(`${base}/customer/${record.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: Number(record.id), ...record.data }),
      });
      if (res.status === 404) {
        yield { id: record.id, notFound: true as const };
        continue;
      }
      if (!res.ok) throwForStatus(res, `PUT /customer/${record.id}`);
      const body = (await res.json()) as { value: Record<string, unknown> };
      yield { id: record.id, data: body.value };
    }
  },

  async *delete(
    ids: AsyncIterable<string>,
    ctx: ConnectorContext
  ): AsyncIterable<DeleteResult> {
    const base = ctx.config["baseUrl"] as string;
    for await (const id of ids) {
      const res = await ctx.http(`${base}/customer/${id}`, { method: "DELETE" });
      if (res.status === 404) {
        yield { id, notFound: true as const };
        continue;
      }
      if (!res.ok) throwForStatus(res, `DELETE /customer/${id}`);
      yield { id };
    }
  },
};

const invoiceEntity: EntityDefinition = {
  name: "invoice",

  schema: {
    id: { description: "Tripletex internal invoice ID.", type: "number", immutable: true },
    invoiceNumber: {
      description: "Human-readable invoice number assigned by Tripletex.",
      type: "number",
      immutable: true,
    },
    invoiceDate: { description: "Invoice date (YYYY-MM-DD).", type: "string", required: true },
    dueDate: { description: "Payment due date (YYYY-MM-DD).", type: "string" },
    amountExcludingVat: { description: "Net amount excluding VAT (NOK).", type: "number" },
    amountIncludingVat: { description: "Gross amount including VAT (NOK).", type: "number" },
    currency: { description: "ISO 4217 currency code (e.g. NOK, EUR).", type: "string" },
    customer: {
      description: "Reference to the customer this invoice belongs to.",
      type: { type: "object" },
    },
  },

  dependsOn: ["customer"],

  async onEnable(ctx: ConnectorContext): Promise<void> {
    await registerSubscription("invoice", ctx);
  },

  async onDisable(ctx: ConnectorContext): Promise<void> {
    await deregisterSubscription("invoice", ctx);
  },

  async *read(ctx: ConnectorContext, since?: string): AsyncIterable<ReadBatch> {
    const params: Record<string, string> = {};
    if (since) params["invoiceDateFrom"] = since;

    let maxDate: string | undefined;
    for await (const page of paginate<Record<string, unknown>>(ctx, "/invoice", params)) {
      for (const item of page) {
        const d = item["invoiceDate"] as string | undefined;
        if (d && (!maxDate || d > maxDate)) maxDate = d;
      }
      yield {
        records: page.map((item) => ({
          id: String(item["id"]),
          data: item,
          // Invoices reference a customer — expose the association explicitly.
          associations:
            item["customer"] && typeof item["customer"] === "object"
              ? [
                  {
                    predicate: "customer",
                    targetEntity: "customer",
                    targetId: String((item["customer"] as { id: number }).id),
                  },
                ]
              : undefined,
        })),
        since: maxDate ?? since,
      };
    }
  },

  async lookup(ids: string[], ctx: ConnectorContext): Promise<ReadRecord[]> {
    const base = ctx.config["baseUrl"] as string;
    const results: ReadRecord[] = [];
    for (const id of ids) {
      const res = await ctx.http(`${base}/invoice/${id}`);
      if (res.status === 404) continue;
      if (!res.ok) throwForStatus(res, `GET /invoice/${id}`);
      const body = (await res.json()) as { value: Record<string, unknown> };
      results.push({ id, data: body.value });
    }
    return results;
  },

  // Invoices in Tripletex are created but generally not updated or deleted once sent.
  async *insert(
    records: AsyncIterable<InsertRecord>,
    ctx: ConnectorContext
  ): AsyncIterable<InsertResult> {
    const base = ctx.config["baseUrl"] as string;
    for await (const record of records) {
      const res = await ctx.http(`${base}/invoice`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(record.data),
      });
      if (!res.ok) throwForStatus(res, "POST /invoice");
      const body = (await res.json()) as { value: { id: number } & Record<string, unknown> };
      yield {
        id: String(body.value.id),
        data: body.value as Record<string, unknown>,
      };
    }
  },
};

// ─── Connector ────────────────────────────────────────────────────────────────

const connector: Connector = {
  metadata: {
    name: "tripletex",
    version: "0.1.0",
    // Tripletex uses session tokens, not standard OAuth2. We use auth: 'none' and
    // implement prepareRequest to inject the session token.
    auth: { type: "none" },
    allowedHosts: ["tripletex.no", "api.tripletex.io"],
    configSchema: {
      baseUrl: {
        type: "string",
        description: "Tripletex API base URL.",
        required: true,
        default: "https://tripletex.no/v2",
      },
      consumerToken: {
        type: "string",
        description:
          "Long-lived consumer token issued by Tripletex. Identifies your integration.",
        required: true,
        secret: true,
      },
      employeeToken: {
        type: "string",
        description:
          "Employee token generated by the Tripletex account owner. Identifies the user context.",
        required: true,
        secret: true,
      },
    },
    environments: {
      production: "https://tripletex.no/v2",
      test: "https://api.tripletex.io/v2",
    },
  },

  /**
   * Inject the session token as HTTP Basic auth on every outbound request.
   * Tripletex uses Basic auth with username '0' and the session token as password.
   */
  async prepareRequest(req: Request, ctx: ConnectorContext): Promise<Request> {
    const token = await getSessionToken(ctx);
    const credentials = btoa(`0:${token}`);
    const headers = new Headers(req.headers);
    headers.set("Authorization", `Basic ${credentials}`);
    return new Request(req, { headers });
  },

  getEntities(): EntityDefinition[] {
    return [customerEntity, invoiceEntity];
  },

  /**
   * Parse an inbound Tripletex webhook payload.
   *
   * Tripletex sends:  { subscriptionId, event, id, value? }
   * `value` is present for create/update events; absent for delete events.
   * The entity name is read directly from the `?entity=` query param in the URL
   * (set by registerSubscription) — no event string parsing needed.
   */
  async handleWebhook(req: Request): Promise<WebhookBatch[]> {
    const entity = new URL(req.url).searchParams.get("entity");
    if (!entity) return []; // malformed URL — ack silently

    const body = (await req.json()) as {
      event: string;
      id: number;
      value?: Record<string, unknown>;
    };

    const action = body.event.slice(body.event.indexOf(".") + 1);
    const record: ReadRecord = {
      id: String(body.id),
      data: body.value ?? {},
      deleted: action === "delete",
    };

    return [{ entity, records: [record] }];
  },

  async healthCheck(ctx) {
    const base = ctx.config["baseUrl"] as string;

    // Verify session token is valid.
    const res = await ctx.http(`${base}/token/session`);
    if (!res.ok) {
      return { healthy: false, message: `Session token check returned ${res.status}` };
    }

    // Verify webhook subscriptions are still active.
    // Tripletex marks a subscription `active: false` when it considers it unhealthy
    // (e.g. repeated delivery failures to the target URL).
    const subscriptionKeys: Record<string, string> = {
      customer: "webhookSubscription_customer",
      invoice: "webhookSubscription_invoice",
    };
    const inactive: string[] = [];
    for (const [entity, key] of Object.entries(subscriptionKeys)) {
      const id = await ctx.state.get<number>(key);
      if (!id) continue; // entity not enabled — nothing to check
      const sub = await ctx.http(`${base}/event/subscription/${id}`);
      if (sub.status === 404) {
        inactive.push(`${entity} (${id} not found)`);
        continue;
      }
      if (!sub.ok) throwForStatus(sub, `GET /event/subscription/${id}`);
      const body = (await sub.json()) as { value: { active: boolean } };
      if (!body.value.active) inactive.push(`${entity} (${id} inactive)`);
    }
    if (inactive.length > 0) {
      return { healthy: false, message: `Webhook subscriptions unhealthy: ${inactive.join(", ")}` };
    }

    return { healthy: true };
  },
};

export default connector;
